/** Closed event-name registry shared by the browser tracker and API boundary. */
export const ANALYTICS_EVENT_NAMES = [
  "page_view",
  "search",
  "filter",
  "sort",
  "autocomplete",
  "nl_parse",
  "result_click",
  "map_view",
  "property_view",
  "project_view",
  "developer_view",
  "community_view",
  "agent_view",
  "report_view",
  "report_download_requested",
  "guide_view",
  "favorite",
  "compare",
  "share",
  "brochure_download",
  "whatsapp_click",
  "call_click",
  "form_start",
  "form_complete",
  "lead_generated",
  "consultation_request_submitted",
  "valuation_requested",
  "ai_conversation",
  "ai_recommendation",
  "ai_handoff",
  "calculator_use",
  "account_register",
  "account_login",
  "saved_search_created",
  "alert_opt_in",
  "hero_search_started",
  "search_filter_changed",
  "scenario_run",
  "search_submitted",
  "search_mode_changed",
  "map_opened",
  "map_layer_changed",
  "market_explorer_filter",
  "market_export",
  "roi_scenario_run",
  "compare_added",
  "compare_compared",
  "shortlist_toggled",
  "ai_tool_result_viewed",
  "3d_atlas_opened",
  "3d_atlas_metric_changed",
  "unit_selected",
  "recently_viewed_cleared",
  "logo_click",
  "team_filter",
  "team_member_call",
  "team_member_whatsapp",
  "directions_click",
  "mobile_menu_open",
  "mobile_menu_item_click",
  "evidence_open",
  "share_open",
] as const;

export type AnalyticsEventName = (typeof ANALYTICS_EVENT_NAMES)[number];

const ANALYTICS_EVENT_NAME_SET: ReadonlySet<string> = new Set(ANALYTICS_EVENT_NAMES);

export function isAnalyticsEventName(name: string): name is AnalyticsEventName {
  return ANALYTICS_EVENT_NAME_SET.has(name);
}
