import type { Locale } from "./i18n";

// Closed UI-template vocabulary only: never translate provider content or user input.
export const calculatorArabic = {
  "Home": "الرئيسية",
  "Investor Tools": "أدوات المستثمر",
  "Calculator tools": "أدوات الحساب",
  "Dubai Property Tools": "أدوات العقارات في دبي",
  "ROI Scenario": "سيناريو العائد",
  "ROI Scenario Calculator": "حاسبة سيناريو العائد على الاستثمار",
  "Rental Yield": "العائد الإيجاري",
  "Rental Yield Calculator": "حاسبة العائد الإيجاري",
  "Mortgage": "التمويل العقاري",
  "Mortgage Calculator": "حاسبة التمويل العقاري",
  "Payment Plan": "خطة الدفع",
  "Payment Plan Calculator": "حاسبة خطة الدفع",
  "Currency": "العملة",
  "Currency Converter": "محول العملات",
  "Model total return over a horizon: rental income, financing and an appreciation assumption you control — with downside / base / upside scenarios.": "نمذج العائد الإجمالي خلال مدة محددة: دخل الإيجار والتمويل وافتراض ارتفاع القيمة الذي تحدده، مع سيناريوهات متحفظة وأساسية ومتفائلة.",
  "Gross and net yield with scheduled rent, vacancy allowance and operating costs separated line by line.": "العائد الإجمالي والصافي مع فصل الإيجار المجدول وبدل الشغور وتكاليف التشغيل بنداً بنداً.",
  "Monthly payment and interest totals by borrower category, with your LTV vs the regulatory maximum clearly separated.": "الدفعة الشهرية وإجمالي الفائدة حسب فئة المقترض، مع فصل نسبة التمويل التي تختارها عن الحد التنظيمي المفترض.",
  "Turn an off-plan plan into a validated cash-flow timeline with amounts, cumulative totals and CSV export.": "حوّل خطة الدفع لعقار على المخطط إلى جدول تدفق نقدي مع التحقق من النسب والمبالغ التراكمية والتصدير بصيغة CSV.",
  "Convert AED amounts with clearly-labeled indicative rates.": "حوّل المبالغ بالدرهم باستخدام أسعار صرف استرشادية موضحة بوضوح.",
  "Gross & net yield": "العائد الإجمالي والصافي",
  "IRR & break-even year": "معدل العائد الداخلي وسنة التعادل",
  "Downside / base / upside comparison": "مقارنة السيناريو المتحفظ والأساسي والمتفائل",
  "Gross vs effective rent": "الإيجار المجدول مقابل الفعلي",
  "Operating cost breakdown": "تفصيل تكاليف التشغيل",
  "Net operating income & yields": "صافي دخل التشغيل والعوائد",
  "Monthly payment (precise)": "الدفعة الشهرية بدقة",
  "Your LTV vs regulatory maximum": "نسبة التمويل المختارة مقابل الحد التنظيمي المفترض",
  "First-year amortization": "جدول السداد للسنة الأولى",
  "Timeline with due labels": "جدول زمني مع مواعيد الاستحقاق",
  "100% total validation": "التحقق من أن مجموع النسب 100%",
  "Cashflow CSV export": "تصدير التدفق النقدي بصيغة CSV",
  "Converted amount": "المبلغ المحول",
  "Indicative rate shown": "سعر صرف استرشادي موضح",
  "No live-FX claim": "ليست أسعار صرف مباشرة",
  "Deterministic calculations with explicit assumptions — results are projections and estimates (non-guaranteed).": "حسابات حتمية بافتراضات واضحة؛ النتائج تقديرات وتوقعات غير مضمونة.",
  "Scenario engine": "محرك السيناريوهات",
  "versioned formulas shared across the platform.": "صيغ حتمية ذات إصدارات مشتركة عبر المنصة.",
  "Methodology and assumptions": "المنهجية والافتراضات",
  "How to read these results": "كيف تقرأ هذه النتائج",
  "Facts": "حقائق",
  "Assumptions": "افتراضات",
  "Projections": "توقعات",
  "your inputs and any listing data.": "مدخلاتك وأي بيانات للعقار.",
  "sliders and fields you control (appreciation, vacancy, rate).": "الحقول التي تتحكم بها، مثل ارتفاع القيمة والشغور ومعدل الفائدة.",
  "computed scenarios.": "سيناريوهات محسوبة.",
  "Estimates and projections only — never guaranteed outcomes.": "تقديرات وتوقعات فقط؛ ليست نتائج مضمونة.",
  "Calculations are deterministic and run entirely in your browser. Rents, prices and yields are scenario inputs — verify against current market data before transacting. Nothing here is investment, legal or tax advice.": "الحسابات حتمية وتعمل بالكامل في متصفحك. الإيجارات والأسعار والعوائد مدخلات للسيناريو؛ تحقق من بيانات السوق الحالية قبل أي معاملة. هذه الأدوات لا تقدم نصائح استثمارية أو قانونية أو ضريبية.",
  "Next step": "الخطوة التالية",
  "Turn a scenario into a shortlist with an advisor.": "حوّل السيناريو إلى قائمة عقارات مختارة بمساعدة مستشار.",
  "Book a consultation": "اطلب استشارة",
  "Purchase price (AED)": "سعر الشراء (درهم)",
  "Annual scheduled rent (AED)": "الإيجار السنوي المجدول (درهم)",
  "Property size": "مساحة العقار",
  "sqft": "قدم²",
  "Drives the service-charge line below.": "تُستخدم لحساب رسوم الخدمات أدناه.",
  "Rent growth per year": "نمو الإيجار سنوياً",
  "Rent growth:": "نمو الإيجار:",
  "per year": "سنوياً",
  "years": "سنوات",
  "Assumption — applied to scheduled rent each year.": "افتراض يُطبق على الإيجار المجدول كل سنة.",
  "Vacancy": "الشغور",
  "Vacancy:": "الشغور:",
  "Assumption — share of the year unoccupied.": "افتراض نسبة الفترة التي يبقى فيها العقار شاغراً.",
  "Capital appreciation per year": "ارتفاع قيمة العقار سنوياً",
  "Capital appreciation:": "ارتفاع قيمة العقار:",
  "Assumption — historical appreciation is not a forecast.": "افتراض؛ ارتفاع القيمة تاريخياً ليس توقعاً للمستقبل.",
  "Investment horizon in years": "مدة الاستثمار بالسنوات",
  "Horizon:": "مدة الاستثمار:",
  "Advanced assumptions & financing (service charge, costs, mortgage)": "افتراضات متقدمة وتمويل (رسوم الخدمات والتكاليف والتمويل العقاري)",
  "Service charge rate": "معدل رسوم الخدمات",
  "Annual, per sqft.": "سنوياً لكل قدم مربع.",
  "Maintenance (AED/yr)": "الصيانة (درهم/سنة)",
  "Management fee": "رسوم الإدارة",
  "Percent of effective rent.": "نسبة من الإيجار الفعلي.",
  "Purchase costs": "تكاليف الشراء",
  "Transfer fee etc. — paid upfront.": "رسوم نقل الملكية وغيرها؛ تُدفع مقدماً.",
  "Exit costs": "تكاليف الخروج",
  "Deducted from the projected sale value.": "تُخصم من قيمة البيع المتوقعة.",
  "Model mortgage financing (annuity, fixed rate)": "نمذجة تمويل عقاري بدفعات منتظمة ومعدل ثابت",
  "Down payment percentage": "نسبة الدفعة المقدمة",
  "Down payment:": "الدفعة المقدمة:",
  "Interest rate": "معدل الفائدة",
  "Interest rate:": "معدل الفائدة:",
  "Term in years": "مدة التمويل بالسنوات",
  "Term:": "المدة:",
  "Scenario": "السيناريو",
  "Downside": "متحفظ",
  "Base": "أساسي",
  "Upside": "متفائل",
  "Net yield for this scenario": "العائد الصافي لهذا السيناريو",
  "projection, not a guarantee": "توقع وليس ضماناً",
  "Scheduled rent −15%": "الإيجار المجدول −15%",
  "Appreciation halved": "خفض افتراض ارتفاع القيمة إلى النصف",
  "Vacancy +3pp": "الشغور +3 نقاط مئوية",
  "Your inputs as entered": "مدخلاتك كما أدخلتها",
  "Scheduled rent +10%": "الإيجار المجدول +10%",
  "Appreciation ×1.5": "افتراض ارتفاع القيمة ×1.5",
  "Vacancy −2pp": "الشغور −2 نقطة مئوية",
  "Gross yield (yr 1)": "العائد الإجمالي (السنة الأولى)",
  "Net yield (yr 1)": "العائد الصافي (السنة الأولى)",
  "Net income (yr 1)": "صافي الدخل (السنة الأولى)",
  "Scheduled rent ÷ purchase price": "الإيجار المجدول ÷ سعر الشراء",
  "Net operating income ÷ purchase price": "صافي دخل التشغيل ÷ سعر الشراء",
  "Cash-on-cash (yr 1)": "العائد على النقد المستثمر (السنة الأولى)",
  "Year-1 net cash": "صافي النقد في السنة الأولى",
  "cash invested": "النقد المستثمر",
  "IRR": "معدل العائد الداخلي",
  "Newton-method IRR over the yearly cashflow series (income + exit proceeds)": "معدل العائد الداخلي بطريقة نيوتن للتدفقات النقدية السنوية (الدخل وحصيلة الخروج)",
  "Break-even year": "سنة التعادل",
  "Beyond": "بعد",
  "Year": "السنة",
  "First year cumulative net income covers the initial cash invested (income payback only)": "أول سنة يغطي فيها صافي الدخل التراكمي النقد المستثمر أولياً (استرداد من الدخل فقط)",
  "not converged": "لم تتقارب النتيجة",
  "Total return": "العائد الإجمالي",
  "Annualized return": "العائد السنوي المركب",
  "Break-even": "التعادل",
  "net cash income": "صافي الدخل النقدي",
  "exit equity": "صافي حقوق الملكية عند الخروج",
  "projected value": "القيمة المتوقعة",
  "exit costs": "تكاليف الخروج",
  "loan balance": "رصيد القرض",
  "Illustrative projection — an estimate, not a guaranteed outcome.": "توقع توضيحي وتقدير، وليس نتيجة مضمونة.",
  "Downside, base and upside scenario comparison": "مقارنة السيناريوهات المتحفظة والأساسية والمتفائلة",
  "Metric": "المؤشر",
  "Scenario derivation is deterministic: downside = rent −15%, appreciation halved, vacancy +3pp; upside = rent +10%, appreciation ×1.5, vacancy −2pp. All three are projections (non-guaranteed).": "اشتقاق السيناريوهات حتمي: المتحفظ يخفض الإيجار 15% وافتراض ارتفاع القيمة إلى النصف ويزيد الشغور 3 نقاط؛ المتفائل يزيد الإيجار 10% وافتراض ارتفاع القيمة بمقدار 1.5 ويخفض الشغور نقطتين. السيناريوهات الثلاثة توقعات غير مضمونة.",
  "Service charge": "رسوم الخدمات",
  "Maintenance": "الصيانة",
  "Management": "الإدارة",
  "of effective rent": "من الإيجار الفعلي",
  "Other": "أخرى",
  "Scheduled monthly rent": "الإيجار الشهري المجدول",
  "Contracted rent before vacancy.": "الإيجار التعاقدي قبل احتساب الشغور.",
  "Service charge (AED/yr)": "رسوم الخدمات (درهم/سنة)",
  "Vacancy allowance": "بدل الشغور",
  "Vacancy allowance:": "بدل الشغور:",
  "Assumption — unoccupied periods reduce effective rent.": "افتراض؛ فترات الشغور تقلل الإيجار الفعلي.",
  "Management fee:": "رسوم الإدارة:",
  "Charged on effective (collected) rent.": "تُحتسب على الإيجار الفعلي المحصل.",
  "Other costs (AED/yr)": "تكاليف أخرى (درهم/سنة)",
  "Gross scheduled rent (yr)": "الإيجار المجدول الإجمالي (سنوي)",
  "Effective rent (yr)": "الإيجار الفعلي (سنوي)",
  "Gross yield": "العائد الإجمالي",
  "Net yield": "العائد الصافي",
  "Gross SCHEDULED rent ÷ purchase price": "الإيجار المجدول الإجمالي ÷ سعر الشراء",
  "Rent decomposition (annual)": "تفصيل الإيجار (سنوي)",
  "scheduled": "مجدول",
  "Vacancy allowance (−)": "بدل الشغور (−)",
  "Effective monthly rent": "الإيجار الشهري الفعلي",
  "Net operating income (yr)": "صافي دخل التشغيل (سنوي)",
  "Operating costs": "تكاليف التشغيل",
  "Where the scheduled rent goes": "توزيع الإيجار المجدول",
  "Effective rent equals scheduled rent minus vacancy allowance. Net yield uses effective rent minus operating costs. Vacancy-adjusted rent is not an average monthly rent.": "الإيجار الفعلي هو الإيجار المجدول بعد خصم بدل الشغور. يعتمد العائد الصافي على الإيجار الفعلي ناقص تكاليف التشغيل. الإيجار المعدل للشغور ليس متوسط الإيجار الشهري.",
  "Property price (AED)": "سعر العقار (درهم)",
  "Borrower category": "فئة المقترض",
  "UAE resident — first property": "مقيم في الإمارات — العقار الأول",
  "UAE resident — additional property": "مقيم في الإمارات — عقار إضافي",
  "Non-resident — first property": "غير مقيم — العقار الأول",
  "Non-resident — additional property": "غير مقيم — عقار إضافي",
  "Property status": "حالة العقار",
  "Ready": "جاهز",
  "Off-plan": "على المخطط",
  "Purpose": "الغرض",
  "Owner-occupied": "السكن الشخصي",
  "Investment": "الاستثمار",
  "Loan term in years": "مدة القرض بالسنوات",
  "Defaults to an LTV 5pp below the regulatory maximum — a scenario input, not a loan eligibility judgment.": "القيمة الافتراضية تقل 5 نقاط مئوية عن الحد التنظيمي المفترض؛ هذه مدخلات سيناريو وليست حكماً على أهلية التمويل.",
  "Assumption — fixed rate, varies by lender.": "افتراض معدل ثابت؛ يختلف باختلاف جهة التمويل.",
  "Estimated monthly payment": "الدفعة الشهرية المقدرة",
  "Loan amount": "مبلغ القرض",
  "Down payment": "الدفعة المقدمة",
  "Total interest": "إجمالي الفائدة",
  "LTV — three separate lines": "نسبة التمويل — ثلاثة جوانب منفصلة",
  "Your scenario LTV": "نسبة التمويل في سيناريوك",
  "Regulatory maximum LTV": "الحد التنظيمي المفترض لنسبة التمويل",
  "preset · as of": "قيمة محددة مسبقاً بتاريخ",
  "Your scenario — the down payment, rate and term above are inputs you chose. This is a scenario input, not a loan eligibility judgment.": "سيناريوك: الدفعة المقدمة والمعدل والمدة مدخلات اخترتها؛ ليست حكماً على أهلية الحصول على قرض.",
  "Lender decision — actual approval, pricing and final LTV are determined solely by lender underwriting. This calculator never implies any lender approval or offer.": "قرار جهة التمويل: الموافقة الفعلية والتسعير ونسبة التمويل النهائية تحددها جهة التمويل وحدها. لا تعني هذه الحاسبة وجود موافقة أو عرض تمويل.",
  "Preset regulatory table, pending compliance re-verification; not currently effective law.": "جدول تنظيمي محدد مسبقاً بانتظار إعادة التحقق من الامتثال؛ لا يُعرض باعتباره قانوناً نافذاً حالياً.",
  "Your scenario exceeds the preset regulatory maximum; treat these numbers as hypothetical.": "يتجاوز سيناريوك الحد التنظيمي المفترض؛ تعامل مع هذه الأرقام على أنها افتراضية.",
  "First-year amortization schedule": "جدول السداد للسنة الأولى",
  "Month": "الشهر",
  "Interest": "الفائدة",
  "Principal": "أصل القرض",
  "Balance": "الرصيد",
  "Assumes a fixed rate, the selected term and no fees. Preset regulatory table is pending compliance re-verification; lender underwriting alone determines actual approval.": "يفترض معدلاً ثابتاً والمدة المختارة دون رسوم. الجدول التنظيمي المفترض ينتظر إعادة التحقق من الامتثال؛ جهة التمويل وحدها تقرر الموافقة الفعلية.",
  "Booking": "الحجز",
  "During construction": "أثناء البناء",
  "On handover": "عند التسليم",
  "Post-handover": "بعد التسليم",
  "Plan structure (percent per stage)": "هيكل الخطة (نسبة كل مرحلة)",
  "Stage": "المرحلة",
  "label": "الاسم",
  "percent": "النسبة",
  "due months from booking (optional)": "أشهر الاستحقاق من الحجز (اختياري)",
  "mo": "شهر",
  "Months from booking — leave empty for milestone/unordered stages": "الأشهر من الحجز؛ اترك الحقل فارغاً للمراحل غير المرتبطة بموعد محدد",
  "Move stage": "نقل المرحلة",
  "up": "للأعلى",
  "down": "للأسفل",
  "Remove stage": "حذف المرحلة",
  "+ Add stage": "+ إضافة مرحلة",
  "Plan does not total 100%": "الخطة تحتاج إلى تصحيح",
  "Each stage must be between 0% and 100%; the total must equal 100% within ±0.01%.": "يجب أن تكون نسبة كل مرحلة بين 0% و100% وأن يساوي المجموع 100% بهامش ±0.01%.",
  "Payment timeline": "الجدول الزمني للدفع",
  "of price": "من السعر",
  "Cashflow CSV": "ملف CSV للتدفق النقدي",
  "Payment plan stages as proportional segments of the total": "مراحل خطة الدفع كنسب من الإجمالي",
  "cumulative": "تراكمي",
  "At booking": "عند الحجز",
  "On plan order": "حسب ترتيب الخطة",
  "Booking +": "الحجز +",
  "Stages with explicit months-from-booking are ordered chronologically; otherwise your declared order is used. Totals": "تُرتب المراحل زمنياً عندما تحدد أشهر الاستحقاق لكل مرحلة؛ وإلا يُستخدم ترتيبك المحدد. المجموع",
  "against a": "مقابل",
  "price.": "كسعر للعقار.",
  "Amount (AED)": "المبلغ (درهم)",
  "Convert to": "التحويل إلى",
  "Indicative rate": "سعر استرشادي",
  "manually maintained, not live FX. Confirm with your bank before transactions.": "يُحدّث يدوياً وليس سعر صرف مباشراً. تحقق من البنك قبل إجراء أي معاملة.",
  "Return composition over time": "مكونات العائد عبر الزمن",
  "Cumulative net rental income + capital appreciation at your assumption · purchase": "صافي دخل الإيجار التراكمي + ارتفاع القيمة وفق افتراضك · الشراء",
  "scenario": "سيناريو",
  "Buy": "الشراء",
  "Yr": "السنة",
  "Stacked area chart of cumulative rental income and capital appreciation by year": "مخطط تراكمي لدخل الإيجار وارتفاع قيمة العقار حسب السنة",
  "Rental income": "دخل الإيجار",
  "Rental income (cum.)": "دخل الإيجار (تراكمي)",
  "Appreciation": "ارتفاع القيمة",
  "Appreciation (assumption)": "ارتفاع القيمة (افتراض)",
  "Deterministic projection from your inputs. Appreciation compounds annually at your stated assumption — historical growth is not a forecast, and total return is a scenario, not a guaranteed outcome.": "توقع حتمي من مدخلاتك. تتراكم زيادة القيمة سنوياً وفق افتراضك؛ النمو التاريخي ليس توقعاً للمستقبل والعائد الإجمالي سيناريو وليس نتيجة مضمونة.",
  "Net operating income": "صافي دخل التشغيل",
  "Running costs": "تكاليف التشغيل",
  "Vacancy loss": "خسارة الشغور",
  "Annual rent decomposition": "تفصيل الإيجار السنوي",
  "computed from the inputs above — deterministic scenario, not a guarantee.": "محسوب من المدخلات أعلاه؛ سيناريو حتمي وليس ضماناً.",
  "Loaded saved scenario": "تم تحميل السيناريو المحفوظ",
  "engine re-runs it with the current version.": "يعيد المحرك حسابه باستخدام الإصدار الحالي.",
  "Invest": "الاستثمار",
  "Investor tools": "أدوات المستثمر",
  "Investor Calculators — Dubai Property Tools": "حاسبات المستثمر — أدوات العقارات في دبي",
  "Investor calculators": "حاسبات المستثمر",
  "Five deterministic Dubai property calculators — ROI scenarios, rental yield, mortgage payments, off-plan payment plans and currency conversion — with assumptions separated from facts.": "خمس حاسبات حتمية للعقارات في دبي: سيناريوهات العائد والإيجار والتمويل وخطط الدفع والعملات، مع فصل الافتراضات عن الحقائق.",
  "Run the numbers before you fall for the photos": "احسب الأرقام قبل أن تختار بناءً على الصور",
  "Five deterministic calculators for Dubai property decisions. Every input is yours, every assumption is labeled, and every result is a scenario — never a guarantee.": "خمس حاسبات حتمية للقرارات العقارية في دبي. أنت تحدد المدخلات، وكل افتراض موضح، وكل نتيجة سيناريو وليست ضماناً.",
  "Open calculator": "فتح الحاسبة",
  "Method, not magic": "منهجية واضحة",
  "How these tools treat numbers": "كيف تتعامل الأدوات مع الأرقام",
  "Deterministic": "حتمية",
  "Labeled": "موضحة",
  "Local": "محلية",
  "same inputs, same outputs, every time. No hidden models.": "المدخلات نفسها تعطي النتائج نفسها دائماً، دون نماذج مخفية.",
  "facts, assumptions and projections are visually separated.": "الحقائق والافتراضات والتوقعات منفصلة بصرياً.",
  "calculations run in your browser; nothing is submitted.": "تعمل الحسابات في متصفحك دون إرسال المدخلات.",
  "Nothing here is investment, legal or tax advice. Verify against current market data before transacting.": "لا تقدم هذه الأدوات نصائح استثمارية أو قانونية أو ضريبية. تحقق من بيانات السوق الحالية قبل إجراء المعاملات."
} as const;
export type CalculatorCopyKey = keyof typeof calculatorArabic;
export function calculatorCopy(locale: Locale) {
  return (key: CalculatorCopyKey): string => locale === "ar" ? calculatorArabic[key] : key;
}

export function paymentDueCopy(label: string, locale: Locale): string {
  if (locale !== "ar") return label;
  if (label === "At booking") return calculatorArabic["At booking"];
  if (label === "On plan order") return calculatorArabic["On plan order"];
  const months = /^Booking \+ (\d+) mo$/.exec(label);
  return months ? `${calculatorArabic["Booking +"]} ${months[1]} ${calculatorArabic.mo}` : label;
}
