import { createHash, randomBytes } from "node:crypto";
import { PrismaClient } from "@prisma/client";
import sharp from "sharp";
import AxeBuilder from "@axe-core/playwright";
import { expect, test } from "./fixtures";
const db = new PrismaClient(), prefix = "direct-publish-" + crypto.randomUUID();
const userId = prefix + "-owner", communityId = prefix + "-community", token = randomBytes(32).toString("hex");
test.beforeAll(async () => {
  const url = new URL(process.env.DATABASE_URL!);
  if (!["db", "postgres", "localhost", "127.0.0.1"].includes(url.hostname)) throw new Error("Disposable database required");
  const role = await db.role.findUniqueOrThrow({ where: { key: "OWNER" } });
  await db.user.create({ data: { id: userId, email: userId + "@example.invalid", emailVerified: new Date(), roles: { create: { roleId: role.id } } } });
  await db.session.create({ data: { userId, tokenHash: createHash("sha256").update(token).digest("hex"), expiresAt: new Date(Date.now() + 3600000), mfaVerifiedAt: new Date() } });
  await db.community.create({ data: { id: communityId, name: prefix, slug: communityId, areaType: "RESIDENTIAL", lat: 25, lng: 55, publicationStatus: "PUBLISHED" } });
});
test.afterAll(async () => {
  const entities = [...await db.property.findMany({ where: { slug: { startsWith: prefix } }, select: { id: true } }), ...await db.agent.findMany({ where: { slug: { startsWith: prefix } }, select: { id: true } })];
  await db.auditLog.deleteMany({ where: { actorId: userId } });
  await db.outboxEvent.deleteMany({ where: { aggregateId: { in: entities.map(row => row.id) } } });
  await db.property.deleteMany({ where: { slug: { startsWith: prefix } } });
  await db.agent.deleteMany({ where: { slug: { startsWith: prefix } } });
  await db.community.delete({ where: { id: communityId } });
  await db.user.delete({ where: { id: userId } });
  const media = await db.mediaAsset.findMany({ where: { originalFilename: { startsWith: prefix } }, select: { id: true } });
  await db.outboxEvent.deleteMany({ where: { aggregateId: { in: media.map(row => row.id) } } });
  await db.mediaProcessingJob.deleteMany({ where: { mediaId: { in: media.map(row => row.id) } } });
  await db.mediaAsset.deleteMany({ where: { id: { in: media.map(row => row.id) } } });
  await db.$disconnect();
});
for (const locale of ["en", "ar"]) for (const [size, viewport] of [["desktop", { width: 1280, height: 900 }], ["mobile", { width: 390, height: 844 }]] as const) {
  test(`${locale} ${size}: publish a property and website staff without an account`, async ({ page, baseURL, context }) => {
    test.setTimeout(120000);
    await page.setViewportSize(viewport);
    await context.addCookies([{ name: "ie_session", value: token, url: baseURL!, httpOnly: true, sameSite: "Lax" }]);
    const root = locale === "ar" ? "/ar" : "", slug = `${prefix}-${locale}-${size}`, title = "Synthetic direct property " + locale + size;
    await page.goto(root + "/admin/properties");
    await page.getByRole("button", { name: "Create property", exact: true }).click();
    const form = page.getByRole("dialog");
    await form.getByLabel("Title", { exact: true }).fill(title);
    await form.getByLabel("URL slug", { exact: true }).fill(slug);
    await form.getByLabel("Latitude", { exact: true }).fill("25"); await form.getByLabel("Longitude", { exact: true }).fill("55");
    await form.getByLabel("Price (AED)", { exact: false }).fill("100");
    await form.getByRole("combobox", { name: "Community", exact: true }).click(); await page.getByRole("option", { name: prefix + " (PUBLISHED)", exact: true }).click();
    await form.getByRole("combobox", { name: "Listing type", exact: true }).click(); await page.getByRole("option", { name: "SALE", exact: true }).click();
    await form.getByRole("combobox", { name: "Listing availability", exact: true }).click(); await page.getByRole("option", { name: "AVAILABLE", exact: true }).click();
    const create = page.waitForResponse(r => new URL(r.url()).pathname === "/api/admin/properties" && r.request().method() === "POST");
    await form.getByRole("button", { name: "Save & publish", exact: true }).click(); expect((await create).status()).toBe(201);
    const property = await db.property.findUniqueOrThrow({ where: { slug }, include: { listings: true } });
    expect(property.publicationStatus).toBe("PUBLISHED"); expect(property.listings[0].publishedAt).not.toBeNull();
    await page.goto(root + "/properties/" + slug); await expect(page.getByRole("heading", { level: 1, name: title, exact: true })).toBeVisible();
    await page.goto(root + "/admin/agents"); await page.getByRole("button", { name: "New team profile", exact: true }).click();
    const member = "Synthetic staff " + locale + size;
    await form.getByLabel("Name", { exact: true }).fill(member); await form.getByLabel("URL slug", { exact: true }).fill(slug + "-staff");
    await form.getByLabel("Job title", { exact: true }).fill("Office manager");
    await expect(form.getByRole("combobox", { name: "Optional AGENT login account", exact: true })).toContainText("No login account needed");
    const photo = form.getByRole("group", { name: "Public team profile photo", exact: true });
    await photo.getByRole("button", { name: "Upload New", exact: true }).click();
    const upload = page.waitForResponse(r => new URL(r.url()).pathname === "/api/media" && r.request().method() === "POST");
    const buffer = await sharp({ create: { width: 32, height: 24, channels: 3, background: { r: locale === "ar" ? 77 : 99, g: size === "mobile" ? 40 : 80, b: 100 } } }).png().toBuffer();
    await photo.getByLabel("Upload new media").setInputFiles({ name: slug + "-staff.png", mimeType: "image/png", buffer });
    expect((await upload).status()).toBe(201);
    await expect(photo.getByText(slug + "-staff.png · done", { exact: true })).toBeVisible();
    expect((await new AxeBuilder({ page }).include('[role="dialog"]').withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([]);
    const save = page.waitForResponse(r => new URL(r.url()).pathname === "/api/admin/agents" && r.request().method() === "POST");
    await form.getByRole("button", { name: "Publish to Team", exact: true }).click(); expect((await save).status()).toBe(201);
    const profile = await db.agent.findUniqueOrThrow({ where: { slug: slug + "-staff" } });
    expect(profile.userId).toBeNull(); expect(profile.publicTeam).toBe(true); expect(profile.publicAdvisor).toBe(false); expect(profile.photoMediaId).toBeTruthy();
    await page.goto(root + "/about/team"); await expect(page.getByRole("link", { name: member, exact: true })).toBeVisible();
    await page.getByRole("link", { name: member, exact: true }).click(); await expect(page.getByRole("heading", { level: 1, name: member, exact: true })).toBeVisible();
    await page.goto(root + "/admin/agents"); await page.getByRole("row").filter({ hasText: member }).getByRole("button", { name: "Edit", exact: true }).click();
    const withdraw = page.waitForResponse(r => new URL(r.url()).pathname === "/api/admin/agents" && r.request().method() === "PATCH");
    await form.getByRole("button", { name: "Save draft", exact: true }).click(); expect((await withdraw).status()).toBe(200);
    expect((await page.request.get("/api/agents/" + slug + "-staff")).status()).toBe(404);
  });
}
