import { createHash, randomBytes } from "node:crypto";
import { PrismaClient } from "@prisma/client";
import { expect, test } from "./fixtures";
const db = new PrismaClient();
const prefix = `market-browser-${Date.now()}-${randomBytes(4).toString("hex")}`;
const token = randomBytes(32).toString("hex"), ownerId = `${prefix}-owner`;
const baseURL = process.env.A11Y_BASE_URL ?? "http://127.0.0.1:3000";
test.beforeAll(async () => {
  if (!["localhost", "127.0.0.1", "web", "web-test"].includes(new URL(baseURL).hostname) || !["db", "postgres", "localhost", "127.0.0.1"].includes(new URL(process.env.DATABASE_URL!).hostname)) throw new Error("Market browser fixtures require the disposable stack.");
  const role = await db.role.findUniqueOrThrow({ where: { key: "OWNER" } });
  await db.user.create({ data: { id: ownerId, email: `${ownerId}@example.invalid`, emailVerified: new Date(), roles: { create: { roleId: role.id } } } });
  await db.session.create({ data: { userId: ownerId, tokenHash: createHash("sha256").update(token).digest("hex"), expiresAt: new Date(Date.now() + 3600000), mfaVerifiedAt: new Date() } });
  await db.marketReport.create({ data: { slug: `${prefix}-report`, title: "Synthetic embed report", body: "Synthetic browser fixture only.\n\n[[market-data:transactions]]\n\n[[market-data:rents]]\n\n[[market-data:metrics]]", status: "PUBLISHED", publishedAt: new Date(Date.now() - 60000), isIllustrative: true, gated: false } });
});
test.afterAll(async () => {
  const sources = await db.importSource.findMany({ where: { name: { startsWith: prefix } }, include: { runs: true } });
  const runs = sources.flatMap((s) => s.runs), ids = runs.map((r) => r.id);
  await db.marketTransaction.deleteMany({ where: { importRunId: { in: ids } } });
  await db.dataQualityIssue.deleteMany({ where: { entityId: { in: ids } } });
  await db.importRecord.deleteMany({ where: { importRunId: { in: ids } } });
  await db.importRun.deleteMany({ where: { id: { in: ids } } });
  await db.importSource.deleteMany({ where: { id: { in: sources.map((s) => s.id) } } });
  await db.auditLog.deleteMany({ where: { actorId: ownerId } });
  await db.marketReport.deleteMany({ where: { slug: `${prefix}-report` } });
  await db.user.deleteMany({ where: { id: ownerId } });
  await db.$disconnect();
});
test("owner uploads a file, maps its columns and reviews changes before applying", async ({ page }) => {
  test.setTimeout(90000);
  const errors: string[] = [];
  page.on("pageerror", (e) => errors.push(e.message));
  await page.context().addCookies([{ name: "ie_session", value: token, url: baseURL, httpOnly: true, sameSite: "Lax" }]);
  await page.goto("/admin/imports");
  await expect(page.getByRole("heading", { name: "Source → validate → review → apply" })).toBeVisible();
  await page.getByLabel("CSV / JSON file (max 500 rows)").setInputFiles({ name: "source-export.csv", mimeType: "text/csv", buffer: Buffer.from("Ref,Day,Area,Type,AED\n0007,2026-01-15,Synthetic browser area,APARTMENT,1250000.25") });
  await expect(page.getByText("source-export.csv · 1 rows", { exact: false })).toBeVisible();
  await page.getByRole("button", { name: "Register market source", exact: true }).click();
  await page.getByLabel("Publisher / source name").fill(`${prefix}-source`);
  await page.getByLabel("Public source URL").fill("https://example.invalid/browser-fixture");
  await page.getByLabel("Methodology and dataset review notes").fill("Synthetic uploaded source for disposable browser fixture only");
  for (const [field, column] of [["externalId", "Ref"], ["date", "Day"], ["areaName", "Area"], ["propertyType", "Type"], ["amountAed", "AED"]]) await page.locator(`#market-map-${field}`).fill(column);
  await page.getByRole("button", { name: "Save source mapping" }).click();
  await page.getByLabel("Source retrieval date").fill(new Date(Date.now() - 3600000).toISOString().slice(0, 16));
  await expect(page.getByRole("button", { name: "Validate market file only" })).toBeEnabled();
  await page.getByRole("button", { name: "Validate market file only" }).click();
  await expect(page.getByRole("heading", { name: "Row review · VALIDATED" })).toBeVisible();
  const apply = page.getByRole("button", { name: "Apply reviewed market dataset" });
  await expect(apply).toBeDisabled();
  const source = await db.importSource.findUniqueOrThrow({ where: { name: `${prefix}-source` } });
  const run = await db.importRun.findFirstOrThrow({ where: { importSourceId: source.id } });
  expect(await db.marketTransaction.count({ where: { importRunId: run.id } })).toBe(0);
  await page.getByText("Inspect changed fields", { exact: true }).click();
  await expect(page.getByText("— → 125000025", { exact: true })).toBeVisible();
  await page.getByLabel("I reviewed the source, dates and proposed changes for this dataset.").check();
  await apply.click();
  await expect(page.getByRole("heading", { name: "Row review · SUCCEEDED" })).toBeVisible();
  expect(await db.marketTransaction.count({ where: { importRunId: run.id } })).toBe(1);
  await page.goto("/market/transactions?community=Synthetic%20browser%20area");
  await expect(page.getByText("Synthetic browser area", { exact: true }).first()).toBeVisible();
  expect(errors).toEqual([]);
});

test("owner sees indexing diagnostics and can complete a direct rebuild", async ({ page }) => {
  await page.context().addCookies([{ name: "ie_session", value: token, url: baseURL, httpOnly: true, sameSite: "Lax" }]);
  await page.goto("/admin/search");
  await expect(page.getByRole("heading", { name: "Search and map index", exact: true })).toBeVisible();
  const rebuild = page.getByRole("button", { name: "Rebuild search now", exact: true });
  await expect(rebuild).toBeEnabled();
  const response = page.waitForResponse((r) => new URL(r.url()).pathname === "/api/admin/search/reindex" && r.request().method() === "POST");
  await rebuild.click();
  expect((await response).status()).toBe(200);
  await expect(page.getByText("search reindex direct completed", { exact: true }).first()).toBeVisible();
  expect(await db.auditLog.count({ where: { actorId: ownerId, action: "search.reindex.direct.completed" } })).toBe(1);
});

test("published report embeds disclose illustrative observations and recover a failed data read", async ({ page }) => {
  let fail = true;
  await page.route("**/api/market/transactions?*", (route) => route.fulfill(fail ? { status: 503, json: { error: "Synthetic report outage" } } : { json: { dataState: "STAGING_FIXTURE", total: 2, agg: { count: 2, illustrativeCount: 2, sourcedCount: 0, medianAmountMinor: "125000000" } } }));
  await page.route("**/api/market/rents?*", (route) => route.fulfill({ json: { dataState: "STAGING_FIXTURE", total: 1, agg: { count: 1, illustrativeCount: 0, sourcedCount: 1, medianRentMinor: "10000000" } } }));
  await page.route("**/api/market/metrics?*", (route) => route.fulfill({ json: { dataState: "STAGING_FIXTURE", metrics: [{ id: "synthetic-embed-metric", metricKey: "TRANSACTION_COUNT", valueNumeric: 2, unit: "COUNT", periodStart: "2026-01-01", isIllustrative: true, sourceName: "Synthetic browser fixture" }] } }));
  await page.goto(`/market/reports/${prefix}-report`);
  await expect(page.getByRole("heading", { name: "Synthetic embed report", exact: true })).toBeVisible();
  const transactions = page.getByRole("region", { name: "Report transactions data" });
  await expect(transactions.getByRole("button", { name: "Retry report data" })).toBeVisible();
  fail = false;
  await transactions.getByRole("button", { name: "Retry report data" }).click();
  await expect(transactions.getByText(/2 illustrative observations included/)).toBeVisible();
  await expect(transactions.getByText("AED 1,250,000", { exact: true })).toBeVisible();
  await expect(page.getByRole("region", { name: "Report rents data" }).getByText("AED 100,000", { exact: true })).toBeVisible();
  await expect(page.getByRole("region", { name: "Report metrics data" }).getByText("Illustrative · Synthetic browser fixture", { exact: true })).toBeVisible();
});
