"use client";

import * as React from "react";
import { api } from "@/lib/api-client";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { EmptyState, LoadingState } from "@/components/common";
import { Plus } from "lucide-react";

interface Redirect { id: string; fromPath: string; toPath: string; statusCode: number; isActive: boolean; hits: number; note: string | null; createdAt: string; updatedAt: string }
interface RedirectForm { fromPath: string; toPath: string; statusCode: string; note: string; isActive: boolean }
const emptyForm = (): RedirectForm => ({ fromPath: "", toPath: "", statusCode: "301", note: "", isActive: false });

export function RedirectsSection({ canEdit }: { canEdit: boolean }) {
  const [entries, setEntries] = React.useState<Redirect[] | null>(null);
  const [loadFailed, setLoadFailed] = React.useState(false);
  const [query, setQuery] = React.useState("");
  const [state, setState] = React.useState("all");
  const [editing, setEditing] = React.useState<Redirect | null>(null);
  const [creating, setCreating] = React.useState(false);
  const [form, setForm] = React.useState<RedirectForm>(emptyForm());
  const [saving, setSaving] = React.useState(false);
  const [changingId, setChangingId] = React.useState<string | null>(null);

  const load = React.useCallback(() => {
    const params = new URLSearchParams();
    if (query.trim()) params.set("q", query.trim());
    if (state !== "all") params.set("state", state);
    api.get<{ redirects: Redirect[] }>(`/api/admin/redirects${params.size ? `?${params}` : ""}`)
      .then((result) => { setLoadFailed(false); setEntries(result.redirects); })
      .catch(() => { setLoadFailed(true); setEntries([]); });
  }, [query, state]);
  React.useEffect(() => { load(); }, [load]);

  const openCreate = () => { setEditing(null); setCreating(true); setForm(emptyForm()); };
  const openEdit = (entry: Redirect) => {
    setEditing(entry);
    setCreating(false);
    setForm({ fromPath: entry.fromPath, toPath: entry.toPath, statusCode: String(entry.statusCode), note: entry.note ?? "", isActive: entry.isActive });
  };

  const save = async (event: React.FormEvent) => {
    event.preventDefault();
    setSaving(true);
    try {
      const input = { fromPath: form.fromPath, toPath: form.toPath, statusCode: Number(form.statusCode), note: form.note || null };
      if (editing) {
        await api.patch("/api/admin/redirects", { ...input, redirectId: editing.id, expectedUpdatedAt: editing.updatedAt, isActive: form.isActive });
        toast.success(form.isActive ? "Redirect saved and active" : "Redirect saved disabled");
      } else {
        await api.post("/api/admin/redirects", input);
        toast.success("Redirect created disabled; verify its destination before enabling");
      }
      setCreating(false);
      setEditing(null);
      load();
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Redirect could not be saved");
      if (error instanceof Error && error.message.toLowerCase().includes("changed since")) load();
    } finally { setSaving(false); }
  };

  const toggle = async (entry: Redirect) => {
    setChangingId(entry.id);
    try {
      await api.post(`/api/admin/redirects/${encodeURIComponent(entry.id)}/state`, { expectedUpdatedAt: entry.updatedAt, isActive: !entry.isActive });
      toast.success(entry.isActive ? "Redirect disabled" : "Redirect enabled");
      load();
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Redirect state could not be changed");
      if (error instanceof Error && error.message.toLowerCase().includes("changed since")) load();
    } finally { setChangingId(null); }
  };

  return <div className="space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-3">
      <div><h1 className="font-display text-2xl font-semibold">Redirects</h1><p className="mt-1 max-w-3xl text-sm text-muted-foreground">Review redirects generated by slug changes and manage approved same-site paths. Destinations are single-hop; new rules start disabled. Test destination pages before enabling.</p></div>
      {canEdit && <Button onClick={openCreate}><Plus className="mr-2 h-4 w-4" />Add redirect</Button>}
    </header>
    <div className="flex flex-wrap gap-3">
      <Input className="max-w-sm" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search source, destination, note" aria-label="Search redirects" />
      <Select value={state} onValueChange={setState}><SelectTrigger className="w-44"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All redirects</SelectItem><SelectItem value="active">Active</SelectItem><SelectItem value="disabled">Disabled</SelectItem></SelectContent></Select>
    </div>
    {entries === null ? <LoadingState rows={4} /> : loadFailed ? <EmptyState title="Redirect list unavailable" description="The protected list could not be loaded. Try again." /> : entries.length === 0 ? <EmptyState title="No redirects found" description="Slug changes in the visual CMS will create their own audited redirect records." /> : <div className="overflow-x-safe rounded-xl border border-border/70">
      <table className="w-full min-w-[900px] text-sm">
        <thead><tr className="border-b border-border/70 text-left text-xs uppercase tracking-wide text-muted-foreground"><th className="p-3">From</th><th className="p-3">To</th><th className="p-3">HTTP</th><th className="p-3">State</th><th className="p-3">Hits</th><th className="p-3">Note</th><th className="p-3">Actions</th></tr></thead>
        <tbody>{entries.map((entry) => <tr key={entry.id} className="border-b border-border/50 align-top">
          <td className="break-all p-3 font-mono text-xs">{entry.fromPath}</td><td className="break-all p-3 font-mono text-xs">{entry.toPath}</td><td className="p-3">{entry.statusCode}</td>
          <td className="p-3"><Badge variant="outline">{entry.isActive ? "ACTIVE" : "DISABLED"}</Badge></td><td className="p-3 num">{entry.hits}</td><td className="max-w-xs p-3 text-xs text-muted-foreground">{entry.note ?? "—"}</td>
          <td className="p-3"><div className="flex gap-1.5">{canEdit && <><Button size="sm" variant="outline" onClick={() => openEdit(entry)}>Edit</Button><Button size="sm" variant={entry.isActive ? "ghost" : "outline"} disabled={changingId === entry.id} onClick={() => void toggle(entry)}>{entry.isActive ? "Disable" : "Enable"}</Button></>}</div></td>
        </tr>)}</tbody>
      </table>
    </div>}

    {canEdit && <Dialog open={creating || editing !== null} onOpenChange={(open) => { if (!open && !saving) { setCreating(false); setEditing(null); } }}>
      <DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-xl">
        <DialogHeader><DialogTitle>{creating ? "Create redirect" : "Edit redirect"}</DialogTitle><DialogDescription>Use normalized same-site public paths only. Chains, cycles, query strings, external hosts, and private/system routes are rejected. New redirects begin disabled.</DialogDescription></DialogHeader>
        <form className="space-y-4" onSubmit={save}>
          <label className="block space-y-1.5 text-sm font-medium">Source path<Input required maxLength={500} pattern="/[A-Za-z0-9._~/-]*" value={form.fromPath} onChange={(event) => setForm({ ...form, fromPath: event.target.value })} placeholder="/old-guide-slug" /></label>
          <label className="block space-y-1.5 text-sm font-medium">Destination path<Input required maxLength={500} pattern="/[A-Za-z0-9._~/-]*" value={form.toPath} onChange={(event) => setForm({ ...form, toPath: event.target.value })} placeholder="/guides/current-guide-slug" /></label>
          <div className="grid gap-3 sm:grid-cols-2">
            <label className="block space-y-1.5 text-sm font-medium">HTTP status<Select value={form.statusCode} onValueChange={(statusCode) => setForm({ ...form, statusCode })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{[301, 302, 303, 307, 308].map((code) => <SelectItem key={code} value={String(code)}>{code}{code === 301 ? " — permanent" : code === 302 ? " — temporary" : ""}</SelectItem>)}</SelectContent></Select></label>
            {!creating && <label className="flex items-center justify-between gap-3 rounded-md border p-3 text-sm"><span><span className="block font-medium">Active</span><span className="text-xs text-muted-foreground">Enabling checks for chains.</span></span><Switch checked={form.isActive} onCheckedChange={(isActive) => setForm({ ...form, isActive })} /></label>}
          </div>
          <label className="block space-y-1.5 text-sm font-medium">Note (optional)<Textarea maxLength={500} rows={3} value={form.note} onChange={(event) => setForm({ ...form, note: event.target.value })} placeholder="Reason for this redirect" /></label>
          <DialogFooter><Button type="button" variant="outline" disabled={saving} onClick={() => { setCreating(false); setEditing(null); }}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? "Saving…" : creating ? "Create disabled redirect" : "Save redirect"}</Button></DialogFooter>
        </form>
      </DialogContent>
    </Dialog>}
  </div>;
}
