"use client";
import * as React from "react";
import { api } from "@/lib/api-client";
import { Link } from "@/lib/router";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
interface Operations { index: { provider: string; size: number; built: boolean }; eligible: number; latestIndexedAt: string | null; pendingRebuilds: number; worker: { ok: boolean; status: string; heartbeatAt: string | null }; truncated: boolean; diagnostics: { listingId: string; title: string; slug: string; reasons: string[]; indexed: boolean | null }[]; history: { id: string; action: string; createdAt: string; details: { count?: number; reason?: string } }[] }
export function SearchOperationsSection() {
  const [data, setData] = React.useState<Operations | null>(null), [error, setError] = React.useState("");
  const [busy, setBusy] = React.useState(false), [onlyIssues, setOnlyIssues] = React.useState(true);
  const load = React.useCallback(async () => { try { setData(await api.get("/api/admin/search")); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Search operations are unavailable."); } }, []);
  React.useEffect(() => { void load(); }, [load]);
  const rebuild = async (mode: "direct" | "queue") => {
    setBusy(true); setError("");
    try { const result = await api.post<{ status: string; count?: number }>("/api/admin/search/reindex", { mode }); await load(); toast.success(result.status === "COMPLETED" ? `Search rebuilt: ${result.count} listings` : "Rebuild queued; completion requires an active worker"); }
    catch (e) { const message = e instanceof Error ? e.message : "Rebuild failed."; await load(); setError(message); }
    finally { setBusy(false); }
  };
  return <section className="space-y-5"><header className="flex flex-wrap items-end justify-between gap-3"><div><p className="kicker">Discovery operations</p><h1 className="mt-1 font-display text-2xl font-semibold">Search and map index</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Compare the canonical inventory with its search projection, inspect exclusion reasons and rebuild. Public search can use a bounded canonical fallback during a projection outage.</p></div><Button variant="outline" onClick={() => void load()} disabled={busy}>Refresh search diagnostics</Button></header>
    {error && <p role="alert" className="rounded-lg border border-destructive/40 p-4 text-sm text-destructive">{error}</p>}
    {!data && !error && <p role="status">Loading search diagnostics…</p>}
    {data && <><div className="grid gap-3 sm:grid-cols-3">{[["Configured provider", data.index.provider], ["Public eligible listings", data.eligible], ["Indexed documents", data.index.size]].map(([label, value]) => <div key={label} className="rounded-xl border bg-card p-5"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 font-display text-2xl">{value}</p></div>)}</div>
      <div className="space-y-3 rounded-xl border bg-card p-5"><div className="flex flex-wrap gap-3"><Badge variant="outline">Index {data.index.built ? "available" : "unavailable"}</Badge><Badge variant="outline">Worker {data.worker.status}</Badge><span className="text-xs text-muted-foreground">{data.pendingRebuilds} pending queue requests · latest projection write {data.latestIndexedAt ? new Date(data.latestIndexedAt).toLocaleString() : "unavailable"}</span></div><p className="text-sm text-muted-foreground">Direct rebuild runs now for up to 1,000 public listings. Queued rebuilds require a live worker heartbeat; the queue cannot complete while the worker is deferred.</p><div className="flex flex-wrap gap-2"><Button onClick={() => void rebuild("direct")} disabled={busy || data.eligible > 1000}>{busy ? "Rebuilding…" : "Rebuild search now"}</Button><Button variant="outline" onClick={() => void rebuild("queue")} disabled={busy || !data.worker.ok}>Queue worker rebuild</Button><Button asChild variant="outline"><Link to="/properties">Open public search</Link></Button></div></div>
      <div className="rounded-xl border bg-card p-5"><h2 className="font-semibold">Inventory inclusion and exclusions</h2><label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={onlyIssues} onChange={(e) => setOnlyIssues(e.target.checked)} />Only show excluded or missing listings</label>{data.truncated && <p className="mt-2 text-sm text-muted-foreground">Diagnostics are limited to the 500 most recently edited listings; projection ID inspection is capped at 10,000.</p>}<div className="mt-4 overflow-auto"><table className="w-full min-w-[520px] text-left text-sm"><thead><tr><th className="p-2">Listing</th><th className="p-2">Projection</th><th className="p-2">Reason</th></tr></thead><tbody>{data.diagnostics.filter((row) => !onlyIssues || row.reasons.length).map((row) => <tr key={row.listingId} className="border-t"><td className="p-2">{row.title}<p className="text-xs text-muted-foreground">{row.slug}</p></td><td className="p-2">{row.indexed === null ? "Local provider" : row.indexed ? "Present" : "Absent"}</td><td className="p-2">{row.reasons.join(", ") || "Eligible"}</td></tr>)}</tbody></table></div>{!data.diagnostics.some((row) => !onlyIssues || row.reasons.length) && <p className="mt-3 text-sm text-muted-foreground">No exclusion or missing-projection issues in this sample.</p>}</div>
      <div className="rounded-xl border bg-card p-5"><h2 className="font-semibold">Rebuild history</h2>{!data.history.length && <p className="mt-3 text-sm text-muted-foreground">No recorded rebuild operations.</p>}<ul className="mt-3 space-y-2">{data.history.map((entry) => <li key={entry.id} className="rounded-lg border p-3 text-sm"><strong>{entry.action.replaceAll(".", " ")}</strong><p className="mt-1 text-xs text-muted-foreground">{new Date(entry.createdAt).toLocaleString()}{entry.details.count !== undefined ? ` · ${entry.details.count} listings` : ""}{entry.details.reason ? ` · ${entry.details.reason}` : ""}</p></li>)}</ul></div>
    </>}
  </section>;
}
